name: pulse
description: Pulse
version: 1.0.0+1
publish_to: none

workspace:
  - packages/*

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  appearance:
    path: packages/appearance
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home:
    path: packages/home
  infrastructure:
    path: packages/infrastructure
  profile:
    path: packages/profile
  session:
    path: packages/session

dev_dependencies:
  alchemist: ^0.14.0
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  melos: ^7.4.1
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

melos:
  scripts:
    analyze:
      run: melos exec --concurrency=6 -- flutter analyze
      description: Run flutter analyze for all packages.

    format:
      run: melos exec --concurrency=6 -- dart format .
      description: Run dart format for all packages.

    test:
      run: melos exec --concurrency=1 -- flutter test
      description: Run flutter test for all packages.

    clean:
      run: melos exec --concurrency=6 -- flutter clean
      description: Run flutter clean in all packages.

    get:
      run: melos exec --concurrency=6 -- flutter pub get
      description: Install dependencies for all packages.
